//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by foo_dsp_effect.rc
//
#define IDCANCEL3                       6
#define IDD_DSP                         101
#define IDD_ECHO                        102
#define IDD_REVERB                      103
#define IDD_PHASER                      104
#define IDD_WAHWAH                      105
#define IDD_PITCH                       106
#define IDD_BANDPASS1                   107
#define IDD_TEMPO                       108
#define IDD_NORCH                       112
#define IDC_SLIDER_MS                   1001
#define IDC_SLIDER_LABEL_MS             1002
#define IDC_SLIDER_AMP                  1003
#define IDC_DRYTIME                     1004
#define IDC_SLIDER_LABEL_AMP            1005
#define IDC_DRYTIMEINFO                 1006
#define IDC_WETTIME                     1007
#define IDC_WETTIMEINFO                 1008
#define IDC_DAMPING                     1009
#define IDC_DAMPINGINFO                 1010
#define IDC_ROOMSIZE                    1011
#define IDC_PHASERSTAGES                1012
#define IDC_ROOMSIZEINFO                1013
#define IDC_PHASERSTAGESINFO            1014
#define IDC_ROOMWIDTH                   1015
#define IDC_PHASERSDRYWET               1016
#define IDC_WAHDEPTH                    1017
#define IDC_ROOMWIDTHINFO               1018
#define IDC_PHASERDRYWETINFO            1019
#define IDC_WAHDEPTHINFO                1020
#define IDC_PHASERSLFOFREQ              1021
#define IDC_WAHRESONANCE                1022
#define IDC_PHASERSLFOFREQINFO          1023
#define IDC_WAHRESONANCEINFO            1024
#define IDC_PHASERSLFOSTARTPHASE        1025
#define IDC_WAHFREQOFFSET               1026
#define IDC_PHASERSLFOSTARTPHASEINFO    1027
#define IDC_WAHFREQOFFSETINFO           1028
#define IDC_PHASERSDEPTH                1029
#define IDC_WAHLFOFREQ                  1030
#define IDC_PHASERSDEPTHINFO            1031
#define IDC_WAHLFOFREQINFO              1032
#define IDC_BANDPASSQINFO2              1033
#define IDC_PHASERSFEEDBACK             1034
#define IDC_WAHLFOSTARTPHASE            1035
#define IDC_PHASERSFEEDBACKINFO         1036
#define IDC_WAHLFOFREQINFO2             1037
#define IDC_WAHLFOPHASEINFO             1038
#define IDD_DYNAMICS                    1039
#define IDC_DISPLAY                     1040
#define IDD_IIR                         1041
#define IDC_IIRFREQ                     1042
#define IDC_PEAKLIMIT                   1042
#define IDC_DYNAMICSPEAKLIMIT           1043
#define IDC_IIRFREQINFO                 1044
#define IDD_TEMPO1                      1045
#define IDD_RATE                        1046
#define IDC_RELEASETIME                 1047
#define IDC_DYNAMICSRELEASETIME         1048
#define IDD_PITCHTEMPO                  1048
#define IDC_IIRQ                        1049
#define IDD_DYNAMICS1                   1049
#define IDC_FASTRATIO                   1050
#define IDC_DYNAMICSSLOWRATIO1          1050
#define IDD_ECHO1                       1050
#define IDC_DYNAMICSFASTRATIO           1051
#define IDD_IIR1                        1051
#define IDC_IIRQINFO                    1052
#define IDD_PHASER1                     1052
#define IDC_SLOWRATIO                   1053
#define IDD_REVERB1                     1053
#define IDC_DYNAMICSSLOWRATIO           1054
#define IDD_WAHWAH1                     1054
#define IDC_IIRGAIN                     1055
#define IDD_TREMELO                     1055
#define IDC_GAIN                        1056
#define IDD_VIBRATO                     1056
#define IDC_DYNAMICSGAIN                1057
#define IDD_VIBRATO1                    1057
#define IDC_IIRGAININFO                 1058
#define IDD_TREMELO1                    1058
#define IDC_DISPLAY_GAIN                1059
#define IDD_CHORUS                      1059
#define IDC_DYNAMICSDISPLAY_GAIN        1060
#define IDD_CHORUS1                     1060
#define IDC_DISPLAY_PEAK                1061
#define IDC_DYNAMICSDISPLAY_PEAK        1062
#define IDC_IIRTYPE                     1063
#define IDC_DISPLAY_RELEASE             1064
#define IDC_DYNAMICSDISPLAY_RELEASE     1065
#define IDC_PITCH                       1066
#define IDC_DISPLAY_FASTRATIO           1067
#define IDC_DYNAMICSDISPLAY_FASTRATIO   1068
#define IDC_PITCHINFO                   1069
#define IDC_DISPLAY_SLOWRATIO           1070
#define IDC_PITCHTYPE                   1070
#define IDC_DYNAMICSDISPLAY_SLOWRATIO   1071
#define IDC_TEMPOTYPE                   1071
#define IDC_TEMPO                       1072
#define IDC_PITCHENABLE2                1072
#define IDC_IIRTYPELABEL                1072
#define IDC_TEMPOINFO                   1073
#define IDC_PITCHENABLED                1073
#define IDC_RATEINFO                    1074
#define IDC_TEMPOINFO2                  1074
#define IDC_RATE                        1075
#define IDC_RATEINFO2                   1075
#define IDC_RATE2                       1076
#define IDC_COMBO2                      1077
#define IDC_TEMPOENABLED                1077
#define IDC_RATENABLED                  1078
#define IDC_PITCH2                      1079
#define IDC_PITCHINFO2                  1080
#define IDC_PITCHTYPE2                  1081
#define IDC_TEMPO2                      1082
#define IDC_TEMPOTYPE2                  1083
#define IDC_DYNAMICSPEAKLIMIT1          1084
#define IDC_DYNAMICSRELEASETIME1        1085
#define IDC_DYNAMICSDISPLAY_RELEASE1    1086
#define IDC_DYNAMICSDISPLAY_FASTRATIO1  1087
#define IDC_DYNAMICSFASTRATIO1          1088
#define IDC_DYNAMICSDISPLAY_SLOWRATIO1  1089
#define IDC_DYNAMICSGAIN1               1090
#define IDC_DYNAMICSENABLED             1091
#define IDC_DYNAMICSDISPLAY_PEAK1       1092
#define IDC_DYNAMICSDISPLAY_GAIN1       1093
#define IDC_SLIDER_MS1                  1094
#define IDC_SLIDER_LABEL_MS1            1095
#define IDC_SLIDER_AMP1                 1096
#define IDC_SLIDER_LABEL_AMP1           1097
#define IDC_ECHOENABLED                 1098
#define IDC_IIRFREQ1                    1099
#define IDC_IIRFREQINFO1                1100
#define IDC_IIRGAIN1                    1101
#define IDC_IIRTYPE1                    1102
#define IDC_IIRENABLED                  1103
#define IDC_IIRGAININFO1                1104
#define IDC_PHASERENABLED               1105
#define IDC_PHASERSTAGES1               1106
#define IDC_PHASERSTAGESINFO1           1107
#define IDC_PHASERSDRYWET1              1108
#define IDC_PHASERDRYWETINFO1           1109
#define IDC_PHASERSLFOFREQ1             1110
#define IDC_PHASERSLFOFREQINFO1         1111
#define IDC_PHASERSLFOSTARTPHASE1       1112
#define IDC_PHASERSLFOSTARTPHASEINFO1   1113
#define IDC_PHASERSDEPTH1               1114
#define IDC_PHASERSDEPTHINFO1           1115
#define IDC_PHASERSFEEDBACK1            1116
#define IDC_PHASERSFEEDBACKINFO1        1117
#define IDC_DRYTIME1                    1118
#define IDC_DRYTIMEINFO1                1119
#define IDC_WETTIME1                    1120
#define IDC_WETTIMEINFO1                1121
#define IDC_DAMPINGINFO1                1122
#define IDC_ROOMSIZE1                   1123
#define IDC_ROOMSIZEINFO1               1124
#define IDC_ROOMWIDTH1                  1125
#define IDC_ROOMWIDTHINFO1              1126
#define IDC_FREEVERBENABLE              1127
#define IDC_DAMPING1                    1128
#define IDC_WAHDEPTH1                   1129
#define IDC_WAHDEPTHINFO1               1130
#define IDC_WAHRESONANCE1               1131
#define IDC_WAHRESONANCEINFO1           1132
#define IDC_WAHFREQOFFSET1              1133
#define IDC_WAHFREQOFFSETINFO1          1134
#define IDC_WAHLFOFREQ1                 1135
#define IDC_WAHLFOFREQINFO1             1136
#define IDC_WAHLFOSTARTPHASE1           1137
#define IDC_WAHLFOPHASEINFO1            1138
#define IDC_CHECK1                      1140
#define IDC_WAHENABLED                  1140
#define IDC_VIBRATOENABLED              1140
#define IDC_TREMELOENABLED              1140
#define IDC_TREMELOFREQ                 1141
#define IDC_TREMELOFREQLAB              1142
#define IDC_TREMELODEPTH                1143
#define IDC_TREMELODEPTHLAB             1144
#define IDC_VIBRATOFREQ                 1145
#define IDC_VIBRATOFREQLAB              1146
#define IDC_VIBRATODEPTH                1147
#define IDC_VIBRATODEPTHLAB             1148
#define IDC_VIBRATOFREQ1                1149
#define IDC_VIBRATOFREQLAB1             1153
#define IDC_VIBRATODEPTH1               1154
#define IDC_VIBRATODEPTHLAB1            1155
#define IDC_TREMELOFREQ1                1156
#define IDC_TREMELOFREQLAB1             1157
#define IDC_TREMELODEPTH1               1158
#define IDC_TREMELODEPTHLAB1            1159
#define IDC_CHORUSDELAYMS               1160
#define IDC_CHORUSDELAYLAB              1161
#define IDC_CHORUSDEPTHMS               1162
#define IDC_CHORUSDEPTHMSLAB            1163
#define IDC_CHORUSLFOFREQ               1164
#define IDC_CHORUSLFOFREQLAB            1165
#define IDC_CHORUSDRYWET                1166
#define IDC_CHORUSDRYWETLAB             1167
#define IDC_CHORUSDELAYMS1              1168
#define IDC_CHORUSDELAYLAB1             1169
#define IDC_CHORUSDEPTHMSLAB1           1170
#define IDC_CHORUSLFOFREQ1              1171
#define IDC_CHORUSLFOFREQLAB1           1172
#define IDC_CHORUSDRYWET1               1173
#define IDC_CHORUSDRYWETLAB1            1174
#define IDC_CHORUSENABLED               1175
#define IDC_CHORUSDEPTHMS1              1176
#define IDC_SLIDER                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1177
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
